[package]
name = "string-to-integer-atoi"
version.workspace = true
edition.workspace = true
description = "Optimal String to Integer (atoi) solution implemented in Rust"

[dependencies]
# No external dependencies required - using only std library

[[bin]]
name = "main"
path = "main.rs" 