[package]
name = "two-sum"
version.workspace = true
edition.workspace = true
description = "Optimal Two Sum solution implemented in Rust using HashMap"

[dependencies]
# No external dependencies required - using only std library

[[bin]]
name = "main"
path = "main.rs" 